stages:
  prepare_data:
    cmd: python src/prepare_data.py 
    deps:
      - src/prepare_data.py
      - src/config.py
    params:
      - data
    outs:
      - data/restaurant_ds

  tokenizer:
    cmd: python src/tokenizer.py
    deps:
      - src/tokenizer.py
      - src/config.py
      - src/prepare_data.py
    params:
      - tokenizer
    outs:
      - data/tokenized_ds
      - results/final_tokenizer

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/config.py
      - data/tokenized_ds
    params:
      - train
    outs:
      - results/final_model
    metrics:
      - results/metrics/metrics.json
